######################## default configuration ####################
baseURL = "https://webmake.dev"
title = "▷Desarrollo Web y Marketing Digital en La Serena | WebMake"
theme = "bizcraft-hugo"
# language
languageName = "Es"
languageCode = "es-Es"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate.css"
[[params.plugins.css]]
link = "plugins/prettyPhoto.css"
[[params.plugins.css]]
link = "plugins/owl/owl.carousel.css"
[[params.plugins.css]]
link = "plugins/owl/owl.theme.css"
[[params.plugins.css]]
link = "plugins/flex-slider/flexslider.css"
[[params.plugins.css]]
link = "plugins/cd-hero/cd-hero.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/style-switcher.js"
[[params.plugins.js]]
link = "plugins/owl/owl.carousel.js"
[[params.plugins.js]]
link = "plugins/jquery.prettyPhoto.js"
[[params.plugins.js]]
link = "plugins/flex-slider/jquery.flexslider.js"
[[params.plugins.js]]
link = "plugins/cd-hero/cd-hero.js"
[[params.plugins.js]]
link = "plugins/isotope.js"
[[params.plugins.js]]
link = "plugins/ini.isotope.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/jquery.counterup.min.js"
[[params.plugins.js]]
link = "plugins/waypoints.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Inicio"
URL = "/"
weight = 1

[[menu.main]]
name = "Servicios"
URL = "servicios"
weight = 2

[[menu.main]]
name = "Portafolio"
URL = "portfolio"
weight = 3

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 4
  
[[menu.main]]
name = "Contacto"
URL = "contacto"
weight = 5


#################### default parameters ################################
[params]
logo = "images/logo-color.svg"
home = "Home"
URL = ""
# Meta data
description = "Somos una agencia joven dedicada a ofrecer servicios especializados en Desarrollo Web, Marketing Digital y Mantenimiento Web con la mejor calidad-precio."
author = "WebMake"
# contact info
address = "La Serena, Chile"
phone = "+56986370396"
email = "hola@webmake.cl"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# footer content
footer_content = "Somos una agencia joven dedicada a ofrecer servicios especializados en Desarrollo Web, Marketing Digital y Mantenimiento Web con la mejor calidad-precio."
# copyright
copyright = "Copyright &copy; 2020 WebMake"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
  
############################# social site ########################
[[params.social]]
name = "facebook"
icon = "fa-facebook" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.facebook.com/webmake.cl/"

[[params.social]]
name = "instagram"
icon = "fa-instagram" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/webmake.cl/"

[[params.social]]
name = "whatsapp"
icon = "fa-whatsapp" # fontawesome icon pack 4.7 | https://fontawesome.com/v4.7.0/icons/
link = "https://wab.cl/webmake.cl"
